package enums;

public enum Endpoint {
    GET_ALL_TASKS,
    GET_ALL_SUBTASKS,
    GET_ALL_EPICS,
    GET_TASK_BY_ID,
    GET_SUBTASK_BY_ID,
    GET_EPIC_BY_ID,
    GET_CERTAIN_EPIC_SUBTASKS,
    GET_PRIORITIZED,
    GET_HISTORY,
    ADD_TASK,
    ADD_SUBTASK,
    ADD_EPIC,
    UPDATE_TASK,
    UPDATE_SUBTASK,
    UPDATE_EPIC,
    DELETE_ALL_TASKS,
    DELETE_ALL_SUBTASKS,
    DELETE_ALL_EPICS,
    DELETE_TASK_BY_ID,
    DELETE_SUBTASK_BY_ID,
    DELETE_EPIC_BY_ID,
    UNKNOWN_METHOD
}
